### PR TITLE
Simplify setup of the ocvalidate

### PR DESCRIPTION
**Pull request by brokeyourbike**
I am using this action myself to test the configs, and it looks much cleaner in my opinion

### CODE REVIEW

**Comment by stevezhengshiqi** [comment]
Hi, thanks for the pr. Just want to make sure, since this repository sometimes use pre release opencore, can opencore-version be the latest opencore commit?

**Comment by brokeyourbike** [comment]
For pre release opencore https://github.com/dortania/build-repo/releases is used as source?
I think it's possible to do this, but some modifications should be done to the GitHub action. Let me take a look.

**Comment by stevezhengshiqi** [comment]
> For pre release opencore https://github.com/dortania/build-repo/releases is used as source?

Yes, or if you can just track the lastes commit from official Opencore repository, that's would be also good.

**Comment by brokeyourbike** [comment]
Now it's possible to use the latest version of OpenCore

**Comment by stevezhengshiqi** [comment]
Looks good to me. Thanks for this workflow!

**Comment by stevezhengshiqi** [comment]
@brokeyourbike Hi, I met a problem that says "Error: Not Found". Could you have a look on that?
Screen Shot 2022-06-13 at 09 26 45

**Comment by brokeyourbike** [comment]
Hi @stevezhengshiqi 
I am checking if the build for the latest commit exists, so I guess at that moment the build was not ready yet

**Comment by stevezhengshiqi** [comment]
@brokeyourbike Makes sense. It takes time for build-repo to build.

**Comment by brokeyourbike** [comment]
Maybe this is an over complicated flow, why would I need to verify existence of the build for last commit if I can just use latest build, but in any case now it's working like this

**Pull request merged**
